[database]
type = "sqlite"
host = "default.sqlite"
port = -1
name = ""

[database.credentials]
username = ""
password = ""

[ratelimit]
type = "memory"
host = ""
port = -1
name = ""

[ratelimit.credentials]
username = ""
password = ""